from .admin_access import UniSkillsAuthenticationForm, dashboard, landing, login_user, logout_user
from .alumni import AlumniRegistrationForm, alumni_dashboard, alumni_page, register_alumni
from .profile import ProfileUpdateForm, profile_page, rating_page
from .student import (
    StudentRegistrationForm,
    SkillPostForm,
    create_skill_post,
    edit_skill_post,
    delete_skill_post,
    moderation_dashboard,
    moderate_skill_post,
    register_student,
    skill_detail_page,
    skills_page,
    student_dashboard,
)
from .booking import (
    BookingForm,
    BookingDecisionForm,
    create_booking,
    respond_booking,
    bookings_page,
    booking_detail,
    cancel_booking,
    mark_session_complete,
)

__all__ = [
    "StudentRegistrationForm",
    "SkillPostForm",
    "BookingForm",
    "BookingDecisionForm",
    "AlumniRegistrationForm",
    "UniSkillsAuthenticationForm",
    "ProfileUpdateForm",
    "landing",
    "register_student",
    "register_alumni",
    "login_user",
    "logout_user",
    "dashboard",
    "student_dashboard",
    "alumni_dashboard",
    "skills_page",
    "skill_detail_page",
    "create_skill_post",
    "edit_skill_post",
    "delete_skill_post",
    "moderation_dashboard",
    "moderate_skill_post",
    "create_booking",
    "respond_booking",
    "bookings_page",
    "booking_detail",
    "cancel_booking",
    "mark_session_complete",
    "alumni_page",
    "profile_page",
    "rating_page",
]
