from .user_management import (
    alumni_dashboard,
    alumni_page,
    bookings_page,
    dashboard,
    delete_skill_post,
    landing,
    login_user,
    logout_user,
    profile_page,
    rating_page,
    register_alumni,
    register_student,
    skill_detail_page,
    skills_page,
    student_dashboard,
)

__all__ = [
    "landing",
    "register_student",
    "register_alumni",
    "login_user",
    "logout_user",
    "dashboard",
    "student_dashboard",
    "alumni_dashboard",
    "skills_page",
    "delete_skill_post",
    "bookings_page",
    "alumni_page",
    "profile_page",
    "rating_page",
    "skill_detail_page",
]
